# Generated by Django 2.2 on 2019-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_site',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
