# Generated by Django 2.2 on 2019-04-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_goods_goods_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_site',
        ),
    ]
