# Generated by Django 2.2 on 2019-04-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goods_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('goods_number', models.IntegerField()),
                ('goods_price', models.FloatField()),
            ],
        ),
    ]
